model:
  type: "gemma3"
  name: "google/gemma-3-4b-it"
  device: "auto"

tasks:
  - name: "classification_open_VQA"
    data_path: "toy_dataset/toy_dataset.tsv"
    base_path: "/home/dcunhrya"

runtime:
  batch_size: 10
  max_new_tokens: 1024
  save_every: 50
  log_first_batch: true
  output_dir: "/home/dcunhrya/vista_eval/results"
  cache_dir: "/home/dcunhrya/models"
